<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es">
    <head>
        <title>Sistema Gestión de Actividades</title>
        <link rel="icon" type="image/png" href="img/CSJ_Favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" type="text/css" href="css/jquery-ui.min.css" />
        <script type="text/javascript" src="js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="js/jquery.alerts.js"></script>
        <link rel="stylesheet" type="text/css" href="css/login.css" media="all">
    </head>
    <body>
        <br>
        <br>
        <?php
        include(MODULO_PATH . "/" . $conf[$modulo]['archivo']);
        ?>  
        <br>
        <br>
    </body>
</html>